[package]
name = "candy"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
lazy_static = "1.5.0"
nalgebra = "0.33.2"

[dependencies]
flume = {version = "0.11.1", default-features=false}
candy_renderers = {path="./renderers"}

[lib]
name = "candy"
path = "src/lib.rs"

[workspaces]
members = [
  ".",
  "renderers"
]
