[package]
name = "candy-shared-types"
version = "0.1.0"
edition = "2024"

[dependencies]
skia-safe.workspace=true
nalgebra.workspace=true
winit.workspace=true
vello.workspace=true
bytemuck.workspace=true
[features]
default = ["skia"]
skia = []
vello = []
